<a href="https://colab.research.google.com/github/Remyar12/CODSOFT/blob/main/Codsoft_Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, recall_score

In [ ]:
data = pd.read_csv("/content/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [ ]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
label = LabelEncoder()
data['Gender'] = label.fit_transform(data['Gender'])
data['Geography'] = label.fit_transform(data['Geography'])
scaler = StandardScaler()
data[['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']] = scaler.fit_transform(data[['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']])
print(data.columns)
columns_to_drop = ['RowNumber', 'CustomerId', 'Surname']
data = data.drop(columns=[col for col in columns_to_drop if col in data.columns])
X = data.drop(columns=['Exited'])
Y = data['Exited']

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
# Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)
Y_predict_log_reg = log_reg.predict(X_test)

In [ ]:
# Random Forest
ran_for = RandomForestClassifier()
ran_for.fit(X_train, Y_train)
Y_predict_ran_for = ran_for.predict(X_test)

In [ ]:
# Gradient Boosting
grad_boost = GradientBoostingClassifier()
grad_boost.fit(X_train, Y_train)
Y_predict_grad_boost = grad_boost.predict(X_test)

In [ ]:
def model_eval(Y_test, Y_predict):
  print('Accuracy is:', accuracy_score(Y_test, Y_predict))
  print('Confusion Matrix is:\n', confusion_matrix(Y_test, Y_predict))
  print('Classification Report is:\n', classification_report(Y_test, Y_predict))
  roc_score = roc_auc_score(Y_test, Y_predict)
  print('ROC AUC Score is:', roc_score)
  return roc_score

In [ ]:
print("Logistic Regression:")
roc_score_log_reg = model_eval(Y_test, Y_predict_log_reg)

Logistic Regression:
Accuracy is: 0.8155
Confusion Matrix is:
 [[1559   48]
 [ 321   72]]
Classification Report is:
               precision    recall  f1-score   support

           0       0.83      0.97      0.89      1607
           1       0.60      0.18      0.28       393

    accuracy                           0.82      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.82      0.77      2000

ROC AUC Score is: 0.5766683925763716


In [ ]:
print("Random Forest:")
roc_score_ran_for = model_eval(Y_test, Y_predict_ran_for)

Random Forest:
Accuracy is: 0.8635
Confusion Matrix is:
 [[1550   57]
 [ 216  177]]
Classification Report is:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.45      0.56       393

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.74      2000
weighted avg       0.85      0.86      0.85      2000

ROC AUC Score is: 0.707455929924899


In [ ]:
print("Gradient Boosting:")
roc_score_grad_boost = model_eval(Y_test, Y_predict_grad_boost)

Gradient Boosting:
Accuracy is: 0.865
Confusion Matrix is:
 [[1547   60]
 [ 210  183]]
Classification Report is:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.47      0.58       393

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.86      0.86      0.85      2000

ROC AUC Score is: 0.7141561014074873
